Adding datasets and script
bioinspirlab/deepsea-foundation-2023 pull request #1
Opened 2023-12-12 07:23 UTC by DinoDany

2023-12-14 19:40 UTC, eor314 requested changes
This looks good with a few minor changes: 

- Remove .DS_Store files from all directories. 
- Add a .gitignore to make sure files like the DS_Store are not tracked in future commits. 
- Make sure the extensions are correct for the various files. 

Once these changes are made, we can merge and make tweaks from there! We'll need to update the readme in particular to note file version, etc.

2023-12-14 19:40 UTC, eor314 commented on Datasets/.DS_Store
Please remove the .DS_Store files from all directories

2023-12-14 19:40 UTC, eor314 commented on Datasets/Scripts/download_FanthomNet_img
Is this a notebook? Is the file name missing an extension?

2023-12-14 19:40 UTC, eor314 commented on Datasets/Fathomnet-dataset.xlsx
Can this file be converted to CSV format? If it stays in xlsx then people will need to convert it and potentially lose some data.

2023-12-14 19:40 UTC, eor314 commented on Datasets/Coco-dataset.csv
Just to double check, this is just the subset used for the experiments, correct? It looks that way with ~1k entries.

2023-12-14 19:40 UTC, eor314 commented on Datasets/Scripts/.DS_Store
Remove.

2023-12-14 19:40 UTC, eor314 commented on Datasets/iNat-landanimals-dataset.xlsx
Again, please save as CSV.

2023-12-14 19:40 UTC, eor314 commented on Datasets/iNat-marineanimals-dataset.xlsx
Please save as CSV

2023-12-14 19:40 UTC, eor314 commented on Scripts/.DS_Store
Please remove.

2023-12-16 05:30 UTC, DinoDany commented on Datasets/.DS_Store
Done

2023-12-16 05:30 UTC, DinoDany commented on Datasets/Fathomnet-dataset.xlsx
Done

2023-12-16 05:30 UTC, DinoDany commented on Datasets/Scripts/download_FanthomNet_img
Corrected

2023-12-16 05:30 UTC, DinoDany commented on Datasets/iNat-landanimals-dataset.xlsx
Done

2023-12-16 05:30 UTC, DinoDany commented on Scripts/.DS_Store
Done

2023-12-16 05:30 UTC, DinoDany commented on Datasets/Coco-dataset.csv
Yes(:

2024-06-20 16:02 UTC, merged

2024-06-20 16:03 UTC, eor314 commented
@DinoDany apologies it took so long to merge this. Thanks for making the changes. Next step will be to put together a README and then I think it is done!